#!/bin/bash

function usage {
	echo "Usage of project_make:"
	echo "project_make [-l|--local] name"
	echo "project_make [-r|--remote]"
	echo "\t-l,--local  = Create local repository"
	echo "\t-r,--remote = Does not create repository."
	echo "\t              Used when repository pulled beforehand."
	echo "Remote is default"
}

function create_remote {
	echo "Creating remote project"	

	mkdir {src,include,build,bin,testdata,submit}

	cp "$BASH_SOURCE"/../../module/project_make/Makefile.skel Makefile

	cp "$BASH_SOURCE"/../../module/project_make/gitignore.skel .gitignore
	chmod 644 .gitignore

	cp "$BASH_SOURCE"/../../module/project_make/main.skel src/main.cpp 
}

function create_local {
	if [ -e "$1" ]
	then
		echo "Name already exists!"
		exit 3
	fi
	
	mkdir "$1"
	
	cd "$1"
	
	mkdir {src,include,build,bin,testdata,submit}
	
	cp "$BASH_SOURCE"/../../module/project_make/Makefile.skel Makefile
	
	cp "$BASH_SOURCE"/../../module/project_make/gitignore.skel .gitignore

	chmod 644 .gitignore
	
	cp "$BASH_SOURCE"/../../module/project_make/main.skel src/main.cpp 

	git init
}

if [ $# -gt 2 ]
then
	echo "Wrong number of arguments!"
	usage
	exit 1
fi

if [ $# -eq 0 ]
then
	#no arguments recieved (remote repos)
	create_remote
	exit 0
fi

case "$1" in
	"-l"|"--local")
		if [ $# -eq 2 ] 
		then
			create_local "$2"
			exit 0
		else
			echo "Name of project has to be specified when creating local project"
			usage
			exit 4
		fi
		;;
	"-r"|"--remote")
		if [ $# -eq 1 ] 
		then
			create_remote
			exit 0
		else
			echo "Cannot specify name when creating remote project"
			usage
			exit 5
		fi
		;;
	*)
		echo "Unknown target ($1) specifier"
		usage
		exit 2
		;;
esac

