#!/bin/bash

function usage {
	echo -e "Usage of project_make:"
	echo -e "project_make [-l|--local] name"
	echo -e "project_make [-r|--remote]"
	echo -e "\t-l,--local  = Create local repository"
	echo -e "\t-r,--remote = Does not create repository."
	echo -e "\t              Used when repository pulled beforehand."
	echo -e "Remote is default"
}

function create_remote {
	echo -e "Creating remote project"	

	mkdir {src,include,build,bin,testdata,submit}

	cp "$source_dir"/module/project_make/Makefile.skel Makefile

	cp "$source_dir"/module/project_make/gitignore.skel .gitignore

	chmod 644 .gitignore

	cp "$source_dir"/module/project_make/main.skel src/main.cpp 
}

function create_local {
	if [ -e "$1" ]
	then
		echo -e "Name already exists!"
		exit 3
	fi
	
	mkdir "$1"
	
	cd "$1"
	
	mkdir {src,include,build,bin,testdata,submit}
	
	cp "$source_dir"/module/project_make/Makefile.skel Makefile
	
	cp "$source_dir"/module/project_make/gitignore.skel .gitignore

	chmod 644 .gitignore
	
	cp "$source_dir"/module/project_make/main.skel src/main.cpp 

	git init
}

# address of root of source dir
source_dir=$(echo $BASH_SOURCE | tr '/' '\n' | head -n -2 | tr '\n' '/' | head -c -1)

if [ $# -gt 2 ]
then
	echo -e "Wrong number of arguments!"
	usage
	exit 1
fi

if [ $# -eq 0 ]
then
	#no arguments recieved (remote repos)
	create_remote
	exit 0
fi

case "$1" in
	"-l"|"--local")
		if [ $# -eq 2 ] 
		then
			create_local "$2"
			exit 0
		else
			echo -e "Name of project has to be specified when creating local project"
			usage
			exit 4
		fi
		;;
	"-r"|"--remote")
		if [ $# -eq 1 ] 
		then
			create_remote
			exit 0
		else
			echo -e "Cannot specify name when creating remote project"
			usage
			exit 5
		fi
		;;
	*)
		echo -e "Unknown target ($1) specifier"
		usage
		exit 2
		;;
esac

