#!/bin/bash

# kill running instances of compton
killall -q compton

# Wait until the processes have been shut down
while pgrep -u $UID -x compton >/dev/null; do sleep 1; done

# start compton
compton --config ~/.config/compton/compton.conf
