#!/bin/bash

# set wallpaper
## only for single monitor setup
## feh --bg-fill ~/Pictures/Wallpapers/active/amd.png 
nitrogen --restore

# set keayboard layouts
setxkbmap -layout us,cz -variant ,qwerty
setxkbmap -option 'grp:alt_shift_toggle'

